ELT:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 17 for SQL Server' # (The ODBC Driver installed on your system)
      server: DESKTOP-EOHPBP3
    
      database: dbt
      schema: Microsoft
      windows_login : True
      trust_cert : True